Add Word Break problem
vseloved/prj-algo2 pull request #15
Opened 2016-10-06 13:40 UTC by ykushch

Solution for the following problems:
* Edit Distance problem (only naive)
* Longest Common Subsequence (only naive)
* Break Word problem (recursive & dynamic programming approach)

2016-10-06 14:59 UTC, vseloved requested changes

2016-10-06 14:59 UTC, vseloved commented on tasks/ykushch/src/main/java/com/ykushch/prjalgo2/task1/WordBreak.java
> +            for (String wordFromDict : dict) {
this means that we'll be doing O(n * dict.size) operations where dict.size >> n (usually). Not good. We can do in O(n)

2016-10-06 14:59 UTC, vseloved commented on tasks/ykushch/src/main/java/com/ykushch/prjalgo2/task4/DistanceRecursive.java
> +}
не хватает вывода списка букв для выравненных строк

2016-10-20 08:56 UTC, ykushch commented
@vseloved please, review changes with updates.

2016-11-08 10:07 UTC, vseloved commented on tasks/ykushch/src/main/java/com/ykushch/prjalgo2/task1/WordBreak.java
> +        isSentenceBrokenIntoWords(s, dict, resultList, memoList);
тут бы не помешала еще проверка на успешное разбитие строки

2016-11-08 10:08 UTC, merged

2016-11-08 18:28 UTC, ykushch commented on tasks/ykushch/src/main/java/com/ykushch/prjalgo2/task1/WordBreak.java
> +        isSentenceBrokenIntoWords(s, dict, resultList, memoList);
она вроде бы по коду ниже есть. Или я что-то не так понял?