string split, travelling salesman, text justification
vseloved/prj-algo2 pull request #9
Opened 2016-09-29 16:57 UTC by DmytroMitin

2016-10-05 12:54 UTC, vseloved requested changes

2016-10-05 12:54 UTC, vseloved commented on tasks/dmitin/lesson1/string_split/App.java
> +            if (dict.contains(left) && list != null) {
В целом, решение выглядит очень элегантно. Но есть одно но! Онон не будет работать за линейное время, т.к. мы не запоминаем негативный результат, т.е. будем снова и снова возвращаться к этим индексам и проверять, есть ли в них разбиение. Впрочем, кажется, это решается добавлением пары строчек кода (которые нужно добавить)...

2016-10-05 12:59 UTC, vseloved commented
все остальное - ок

2016-10-06 07:56 UTC, DmytroMitin commented on tasks/dmitin/lesson1/string_split/App.java
> +            if (dict.contains(left) && list != null) {
Исправил. https://github.com/vseloved/prj-algo2/pull/9/commits/36cb1f9efcd5fe06a23dc8690c1ac36c96a05835

2016-10-06 07:56 UTC, merged